version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'laravelapp'
    container_name: app
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "4000:3306"
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 9011:80
